### ISSUE TITLE
效率分析功能中线性轴上出现不明显示

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#10]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、实例统计柱状图

![qq 20170615105309](https://user-images.githubusercontent.com/29417531/27163245-baba1ad2-51b8-11e7-9926-2618e778e43a.png)

**Comment by sherlyle** [comment]
已更换插件

**Comment by liangyu1937** [comment]
已经修改
