### ISSUE TITLE
效率分析功能中任务状态统计拼图消失

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#11]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、选择相同的开始和结束时间

![qq 20170615105519](https://user-images.githubusercontent.com/29417531/27163306-0720bc1e-51b9-11e7-9438-151a3c016439.png)

**Comment by sherlyle** [comment]
此问题为旧版本问题，已修复
