### ISSUE TITLE
效率分析功能中柱状图实例提示方向不统一

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#13]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、在横轴上移动鼠标
6、观察实例提示变化

![qq 20170615110126](https://user-images.githubusercontent.com/29417531/27163421-e1a7e2ea-51b9-11e7-8bcb-ca00f2851ac5.png)

**Comment by sherlyle** [comment]
插件根据数据多少自己判断向上向下，插件已更换

**Comment by liangyu1937** [comment]
已经更换插件
