### ISSUE TITLE
效率分析功能中人员/院系提示简单

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#14]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、下拉页面查看实例列表
![qq 20170615110126](https://user-images.githubusercontent.com/29417531/27163473-31e54bd0-51ba-11e7-8756-39f6d42cf6e2.png)

**Comment by sherlyle** [comment]
已作修改
