### ISSUE TITLE
效率分析功能中服务统计列表排版空余

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#15]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、下拉查看实例列表
![qq 20170615110649](https://user-images.githubusercontent.com/29417531/27163537-a3daef7e-51ba-11e7-82ec-aff11def58f3.png)

**Comment by sherlyle** [comment]
下一版本中可以看到

**Comment by liangyu1937** [comment]
已经解决
