### ISSUE TITLE
效率分析功能中实例列表无当前实例状态提示

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#17]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、下拉查看实例列表
![qq 20170615110649](https://user-images.githubusercontent.com/29417531/27163632-56325e28-51bb-11e7-9fc1-938c596e8fa0.png)

**Comment by sherlyle** [comment]
以增加相应状态的提示。
