### ISSUE TITLE
效率分析功能中实例显示框中关闭按钮显示异常

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#18]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、选择一个实例数打开
![qq 20170615110649](https://user-images.githubusercontent.com/29417531/27163684-c618a918-51bb-11e7-8e41-896e93a837ba.png)

**Comment by sherlyle** [comment]
此按钮已去除
