### ISSUE TITLE
效率分析功能中拼图已办模块取消选择后列表数据无改变

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#19]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、选择已办拼图
6、取消选择已办拼图
![qq 20170615110649](https://user-images.githubusercontent.com/29417531/27163722-00a75480-51bc-11e7-907d-018a17269971.png)

**Comment by sherlyle** [comment]
已修复

**Comment by liangyu1937** [comment]
比例拼图已经修复，修复后又出现拼图异常的情况
![image](https://user-images.githubusercontent.com/29417531/27413852-7821376e-5730-11e7-8d02-429c4e12e5da.png)
