### ISSUE TITLE
效率分析功能中已办查询无数据

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#20]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、选择已办拼图
6、在实例列表中选择一个实例的查询按钮
![qq 20170615110649](https://user-images.githubusercontent.com/29417531/27163805-72168c8a-51bc-11e7-96b6-876eb858115a.png)

**Comment by sherlyle** [comment]
已修改
