### ISSUE TITLE
效率分析功能中最短时间不具体

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#21]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、选择待办拼图
![qq 20170615110649](https://user-images.githubusercontent.com/29417531/27163849-b3ab9b5e-51bc-11e7-84d7-37602c4dce26.png)

**Comment by sherlyle** [comment]
时间是否需要修改

**Comment by marstone** [comment]
可再细化一下，5分钟内可显示具体分钟，1分钟内再不做显示吧。
另，对步骤的三种完成时间，都可以增加增加如下说明：
“步骤的完成时间是指：该步骤上的任务的产生时间到办理时间之间的差值，对于尚未办理的任务，使用产生时间到当前时间的差值计算”
实例的也可以增加类似说明。 @sherlyle
