### ISSUE TITLE
效率分析功能中步骤对话框页面显示错误

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#22]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、点击步骤数进入步骤对话框
6、选择页数
![default](https://user-images.githubusercontent.com/29417531/27164446-f509c46a-51bf-11e7-9986-62c6aca119d2.png)

**Comment by sherlyle** [comment]
已修复
