### ISSUE TITLE
效率分析功能中隐藏箭头位置偏移

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#23]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、点击步骤数进入步骤对话框
6、选择一列展开功能
![default](https://user-images.githubusercontent.com/29417531/27164527-7d076354-51c0-11e7-9158-0407e5410018.png)

**Comment by sherlyle** [comment]
右键弹出工具框功能已去除，对应的功能都去除
