### ISSUE TITLE
效率分析功能中升序/降序图标显示重复

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#24]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、点击步骤数进入步骤对话框
6、选择一列显示选项
![qq 20170615113614](https://user-images.githubusercontent.com/29417531/27164581-d85a79bc-51c0-11e7-994a-f2b3d6c3b6b8.png)

**Comment by sherlyle** [comment]
右键弹出工具框功能已去除，对应的功能都去除
