### ISSUE TITLE
效率分析功能中不同的标题显示不同的升降序

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#25]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、点击步骤数进入步骤对话框
6、选择各显示选项
7、选择不同的升序降序
![default](https://user-images.githubusercontent.com/29417531/27164718-b7f9ef26-51c1-11e7-9a03-28a6a64e7241.png)

**Comment by sherlyle** [comment]
插件自带的，是否需要修改

**Comment by marstone** [comment]
@liangyu1937 同一个表格的确可以有多个字段参与排序，只是此处看不出排序的优先级。建议不作修改。
