### ISSUE TITLE
效率分析功能中流程标题锁定后编号消失

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#27]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、点击步骤数进入步骤对话框
6、在列表中选定一列锁定
![default](https://user-images.githubusercontent.com/29417531/27164829-841eba0a-51c2-11e7-9c0d-44d82ba48299.png)

**Comment by sherlyle** [comment]
右键弹出工具框功能已去除，对应的功能都去除
