### ISSUE TITLE
效率分析功能中升序/降序选择，无需打开列表

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#28]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、点击步骤数进入步骤对话框
6、选择流水号标题点击，调整升序降序
![default](https://user-images.githubusercontent.com/29417531/27164854-c195c0ae-51c2-11e7-913c-502c61ed0e3b.png)

**Comment by sherlyle** [comment]
排序打开列表已去除
