### ISSUE TITLE
效率分析功能中重复的关闭按钮

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#29]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、点击步骤数进入步骤对话框
![default](https://user-images.githubusercontent.com/29417531/27164892-fcdd5fbe-51c2-11e7-860c-5b38d264e2c8.png)

**Comment by sherlyle** [comment]
已去除重复删除按钮
