### ISSUE TITLE
效率分析工作流下拉框显示不全

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#3]
复现步骤：
1、使用火狐浏览器53.0.3 (32 位)版
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
![qq 20170615101459](https://user-images.githubusercontent.com/29417531/27162497-29531778-51b4-11e7-8e72-69ffe3f04580.png)

**Comment by sherlyle** [comment]
页面布局已作出调整
