### ISSUE TITLE
效率分析功能中小数查询页面跳转成功

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#31]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、点击步骤数进入步骤对话框
6、输入2.3页数
![qq 20170619145758](https://user-images.githubusercontent.com/29417531/27273031-c0dbf3fa-54ff-11e7-8e05-3e7e9895a0db.png)

**Comment by sherlyle** [comment]
插件自带，一般不影响使用。

**Comment by liangyu1937** [comment]
用户使用的时候没有多大可能使用小数，但是在输入小数后是可以正常搜索的，对于产品的质量会产生质疑。

**Comment by marstone** [comment]
@liangyu1937 已标记为 wontfix，理由：
1.插件问题，我们无法控制，也不会因此而换控件
2.这个问题很普遍，京东、贴吧等几乎所有网站都有这个问题，但不会有人质疑他们的质量
