### ISSUE TITLE
效率分析功能中页面选择按钮排版混乱

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#34]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、在实例列表中选择实例数
6
![qq 20170619145758](https://user-images.githubusercontent.com/29417531/27273242-bfa1b244-5500-11e7-9c52-9bfaa48f53d3.png)
、在打开的对话框中，选择两个标题进行锁定

**Comment by sherlyle** [comment]
这个问题已经修复
