### ISSUE TITLE
效率分析功能中已办拼图模块数据缺少

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#37]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、选择拼图已办区域
6、查看下表
![qq 20170619145758](https://user-images.githubusercontent.com/29417531/27273524-fa2c0990-5501-11e7-82cc-cd1637abed57.png)

**Comment by sherlyle** [comment]
已修复

**Comment by liangyu1937** [comment]
![image](https://user-images.githubusercontent.com/29417531/28108140-16aa9b2c-671d-11e7-9191-40b325cd4928.png)
待办的区域有实例拼图显示，但是为什么列表中没有步骤数！就是这样设计的吗？

**Comment by liangyu1937** [comment]
![qq 20170712111755](https://user-images.githubusercontent.com/29417531/28108471-2d32ed9e-671e-11e7-9ed9-076fd156ea4f.png)

待办数据显示仍然不全

**Comment by marstone** [comment]
请 @sherlyle 在“已修复”时给一下“含有该修复的源代码提交时间”，已避免测试了未更新的版本。

**Comment by sherlyle** [comment]
已修复

**Comment by liangyu1937** [comment]
已经验证
