### ISSUE TITLE
效率分析功能中已办的实例步骤统计中，出现待办状态

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#38]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、选择拼图已办区域
6、下列表中找到步骤统计数字点击
7、在弹出的对话框中向后页面选择
![qq 20170619145758](https://user-images.githubusercontent.com/29417531/27273575-39decea6-5502-11e7-81c1-e7996f080435.png)

**Comment by sherlyle** [comment]
功能已修复。
