### ISSUE TITLE
效率分析功能中合计统计行相关数据缺失，功能未实现

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#39]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、刷新，查看下方实例统计列表
![qq 20170619145758](https://user-images.githubusercontent.com/29417531/27273662-8ca9d838-5502-11e7-8d28-6904c75a58da.png)

**Comment by sherlyle** [comment]
已修复

**Comment by liangyu1937** [comment]
已验证
![default](https://user-images.githubusercontent.com/29417531/29113730-7f79f874-7d24-11e7-8f36-4a130a1982ee.png)
