### ISSUE TITLE
效率分析功能刷新按钮需重新排版

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#4]
复现步骤：
1、使用火狐浏览器53.0.3 (32 位)版
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
![qq 20170615102255](https://user-images.githubusercontent.com/29417531/27162634-ef9926ca-51b4-11e7-9990-ab6c28d0c041.png)

**Comment by sherlyle** [comment]
已重新排版

**Comment by liangyu1937** [comment]
建议继续修改，目前的位置。依然不太友好。与比例拼图的位置不够柔和，能否将按钮整合到实例列表或搜索区域，或者页面设置为自动跳转。
![qq 20170619145758](https://user-images.githubusercontent.com/29417531/27274675-e1f29a6a-5506-11e7-8e4d-d95a4ae3eee0.png)

**Comment by marstone** [comment]
@sherlyle  建议移动到“工作流”的选择框后面紧跟着，并缩小此按钮和选择框高度一致。
可考虑去掉按钮边框仅保留图标即可。

@liangyu1937 这不是个必须的按钮，将来应该可以去掉，目前存在的价值只是因为功能还不够稳定，有可能需要手动触发。
