### ISSUE TITLE
效率分析功能中实例数/步骤数统计详情列表显示较少

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#40]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、选择一个服务的实例数/步骤数点开
6、列表中选择60/页列
7、不使用滚动条仅能查看4行数据
![qq 20170619145758](https://user-images.githubusercontent.com/29417531/27273730-ee18e6a4-5502-11e7-8937-a7cb6455d4c9.png)

**Comment by sherlyle** [comment]
这个该是之前老的版本了，请使用最新程序测试。

**Comment by marstone** [comment]
已更新到"20170620-214222" @liangyu1937 @sherlyle
