### ISSUE TITLE
效率分析功能中隐藏选项栏不可自动收回

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#41]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、选择一个服务的实例数/步骤数点开
6、打开流水号选项栏，选择升序/降序
7、列表未能收回
![qq 20170619145758](https://user-images.githubusercontent.com/29417531/27273791-2f6096e8-5503-11e7-98e6-4277b98d66d3.png)

**Comment by sherlyle** [comment]
弹框排序工具已去除，不需要该功能。
