### ISSUE TITLE
效率分析功能中实例数/步骤数统计详情列表各列会随意拉伸

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#42]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、选择一个服务的实例数/步骤数点开
6、鼠标移动到一列的边线，拉伸
![qq 20170619145758](https://user-images.githubusercontent.com/29417531/27273849-60193b32-5503-11e7-9e12-d5326203d85e.png)

**Comment by marstone** [comment]
非常规操作，不予修复，请关闭。
@liangyu1937
