### ISSUE TITLE
效率分析功能中任务状态比例拼图选择待办或已办，实例状态图无改变

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#5]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
4、点击比例图中待办
5、再点击已办
![qq 20170615103135](https://user-images.githubusercontent.com/29417531/27162827-fd91222c-51b5-11e7-9192-156757719acb.png)

**Comment by sherlyle** [comment]
已修改
