### ISSUE TITLE
dashboard流程管理，主页左侧任务栏空闲去区域较大

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#55]
复现步骤
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170622-111316
![image](https://user-images.githubusercontent.com/29417531/27522277-4337e01e-5a57-11e7-8523-0530945e0f5f.png)

**Comment by marstone** [comment]
@liangyu1937 这部分是响应时的，屏幕宽度小时会自动缩进变成弹出式的

**Comment by liangyu1937** [comment]
之前测试过缩小的情况，可能是我电脑屏幕大小的原因，缩小后变为弹出式，但下方依然会有一条空余空间，只是相比展开的情况缩小了很多。
![image](https://user-images.githubusercontent.com/29417531/27522903-10da4b84-5a5c-11e7-99b1-399ccc4b7cdc.png)

**Comment by marstone** [comment]
@liangyu1937 不是手动缩进，是对于小屏自动缩进，如图：
![image](https://user-images.githubusercontent.com/615968/27545355-310ded50-5ac2-11e7-819c-3db5ca3ddba6.png)
另外，此处布局是第三方设计的主题，在换整个UI框架前不考虑修改这种两可的细节。
