### ISSUE TITLE
dashboard中实例管理搜索方式可以加入发起人搜索

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#57]
一、实际使用中，加入发起人搜索会更方便查找

**Comment by marstone** [comment]
我记得支持发起人搜索？但只是学工号
关键字搜索框，应该支持学工号、tag、标题、流水号 4种
但不支持使用“实名”搜索，这个目前有技术上的限制，较难实现
（比如同名等问题，导致模糊查询性能过低，选择牺牲功能）
实际使用上：
建议1：用户可以先查询该用户学工号，再精确查询
建议2：将需要查询的内容做到标题中或者tag中

**Comment by marstone** [comment]
已增加到“全文检索”的里程碑，尚无开发计划。 @liangyu1937

**Comment by liangyu1937** [comment]
![qq 20170630113851](https://user-images.githubusercontent.com/29417531/27722605-43e3c626-5d9b-11e7-81cd-dcdda043d1b9.png)

![qq 20170630113859](https://user-images.githubusercontent.com/29417531/27722627-5fe72200-5d9b-11e7-94c0-769dbeda2278.jpg)

**Comment by marstone** [comment]
@sherlyle 请将此处提示改成：实例名、流水号、发起人帐号、标签
