### ISSUE TITLE
效率分析功能中实例状态比例拼图提示不明确（此为偶然现Bug）

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#6]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、反复点击任务比例拼图中已办和待办
![qq 20170615103449](https://user-images.githubusercontent.com/29417531/27162877-545bc832-51b6-11e7-80c8-28d514091733.png)

**Comment by sherlyle** [comment]
@marstone @singlealive 反复点击以及点击太快会导致后台获取数据取错,或者取不到数据

**Comment by sherlyle** [comment]
已修复

**Comment by liangyu1937** [comment]
回归测试通过
