### ISSUE TITLE
dashboard查看数据中按钮与下拉框排版的位置偏差

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#61]
复现步骤
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170622-111316
3、选择查看数据
![qq 20170627164759](https://user-images.githubusercontent.com/29417531/27618693-6ac2f4a8-5bf0-11e7-8431-2442be1e665e.png)

**Comment by marstone** [comment]
@sherlyle 请改到一行中吧
另，"工作流"三个字可以不要了（是术语、且下拉框"请选择"也可表达此含义），直接select后面跟俩按钮。第二个按钮字样改成”新窗口查看“

**Comment by sherlyle** [comment]
已修改

**Comment by liangyu1937** [comment]
调整后的按钮大小不一致
