### ISSUE TITLE
dashboard效率分析中实例列表中右边框消失

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#62]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、刷新
![qq 20170627095007](https://user-images.githubusercontent.com/29417531/27618790-eef5505e-5bf0-11e7-843c-9f6695475ebc.png)

**Comment by sherlyle** [comment]
下一版本可以看到

**Comment by sherlyle** [comment]
已修复

**Comment by liangyu1937** [comment]
![image](https://user-images.githubusercontent.com/29417531/28107945-57fa3b88-671c-11e7-9552-3816953155a8.png)
可否修改表格的边框，包括“操作”两个字的位置
