### ISSUE TITLE
dashboard选择实例管理实例查询中的状态栏会无操作填出状态

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#64]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、选择实例管理
![qq 20170629145346](https://user-images.githubusercontent.com/29417531/27675065-07325316-5cdb-11e7-8b09-5a1005941bf3.png)

**Comment by sherlyle** [comment]
需求是状态默认显示进行中
