### ISSUE TITLE
dashboard实例管理导出实例后文件无法使用

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#65]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、选择实例管理
4、选择一个实例导出
![qq 20170629151504](https://user-images.githubusercontent.com/29417531/27678197-eb403806-5ce6-11e7-9d26-ca8c381d53c6.png)

**Comment by sherlyle** [comment]
下一个版本中可以看到

**Comment by liangyu1937** [comment]
这个问题在中山大学的dasboard中是正常可以到处文件的

**Comment by sherlyle** [comment]
文件名乱码等都可以测试了，出现乱码浏览器为火狐。
