### ISSUE TITLE
关于dashboard比例拼图的改进

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#68]
一些用户使用dashboard后对比例拼图显示实例数和流程数提出新的需求
1、用户希望更直观看到每个流程使用情况，由高到低的顺序去显示
2、在显示图中就可以看到，每个流程状态的统计，而不需要去查询出来再去自己统计

**Comment by marstone** [comment]
和 #47 重复，这是app级的统计，还有些其他规划，请先在该issue上追加评论
@liangyu1937
