### ISSUE TITLE
比例拼图，各拼图可随意拖拽出来

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#72]
复现步骤：
1、火狐浏览器54.0.1(32 位)
2、登陆dashboard@Version 20170710-161926版
![image](https://user-images.githubusercontent.com/29417531/28105518-4c3a2902-6712-11e7-9340-74437cb9dffb.png)

**Comment by sherlyle** [comment]
@marstone 拖拽动画是否需要去除？

**Comment by marstone** [comment]
插件自带的功能，我认为算是个用途不大的小功能，不算是bug
