### ISSUE TITLE
databinding解绑表单后，仍然可以在查看数据中出现

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#73]
复现步骤：
1、火狐浏览器54.0.1(32 位)
2、登陆dashboard@Version 20170710-161926版
3、查看数据中选择一个流程
4、在后台中解绑该流程中的一个表单
![image](https://user-images.githubusercontent.com/29417531/28106483-9940b3ca-6716-11e7-937d-7567b07f8375.png)

![image](https://user-images.githubusercontent.com/29417531/28106513-b3ab04f4-6716-11e7-8c9f-17df9a6be6be.png)

**Comment by marstone** [comment]
解绑后api会给出空的绑定关系，请 @sherlyle 判断一下去掉。注意不仅group如此，field也是同样约定。

**Comment by sherlyle** [comment]
已修改

**Comment by liangyu1937** [comment]
已经验证
