### ISSUE TITLE
效率分析功能中坐标竖轴消失

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#8]
复现步骤：
1、火狐浏览器53.0.3 (32 位)
2、登陆dashboard@Version 20170612-175108版
3、在我的管理的流程中选择一个配置好的服务
4、点击效率分析
5、实例统计柱状图
![qq 20170615104549](https://user-images.githubusercontent.com/29417531/27163086-b402ba06-51b7-11e7-9b66-ae6c9d679de8.png)

**Comment by sherlyle** [comment]
已换插件

**Comment by liangyu1937** [comment]
1、更换的插件，是英文。同样是选取时间范围，既有英文又有中文，比较混乱。
2、插件的选取我个人的建议是简单、用户易操作，我站在用户的角度讲，目前的插件我不可能很快就弄懂它的使用方法
![qq 20170619145758](https://user-images.githubusercontent.com/29417531/27275195-f634875c-5508-11e7-9a30-ac6a2e4b5913.png)

**Comment by marstone** [comment]
建议只保留一组（下面那组），语言最好可以调整。 @sherlyle
