### ISSUE TITLE
使用不同引擎版本的通知问题

### ISSUE THREAD

**Issue by liangyu1937** [infoplus/operation-center#84]
问题：
一、阿里云引擎通知
NOTIFICATION_TITLE和NOTIFICATION_CONTENT配置，流程通知中不配置，不发送通知
NOTIFICATION_TITLE和NOTIFICATION_CONTENT配置，流程通知中只配置标题不配置内容，不发送
NOTIFICATION_TITLE和NOTIFICATION_CONTENT不配置，流程中不配置，不发送
流程中配置，NOTIFICATION_TITLE和NOTIFICATION_CONTENT不配置，发送成功
流程中配置，NOTIFICATION_TITLE和NOTIFICATION_CONTENT配置，发送成功
结论：只有流程编辑器中的标题和内容同时配置才能发送通知，引擎版本为v2.0.20170817-232722

二、某大学引擎通知
NOTIFICATION_TITLE和NOTIFICATION_CONTENT配置，流程通知中不配置，发送通知
NOTIFICATION_TITLE和NOTIFICATION_CONTENT配置，流程通知中只配置标题不配置内容，不发送
NOTIFICATION_TITLE和NOTIFICATION_CONTENT不配置，流程中不配置，(校方正在使用未能验证)
流程中配置，NOTIFICATION_TITLE和NOTIFICATION_CONTENT不配置，(校方正在使用未能验证)
流程中配置，NOTIFICATION_TITLE和NOTIFICATION_CONTENT配置，发送成功
结论：NOTIFICATION_TITLE和NOTIFICATION_CONTENT，和流程中各自单独配置都能成功发送通知。引擎版本v2.0.20170713-193018

三、长春本地引擎通知
NOTIFICATION_TITLE和NOTIFICATION_CONTENT配置，流程通知中不配置，发送通知
NOTIFICATION_TITLE和NOTIFICATION_CONTENT配置，流程通知中只配置标题不配置内容，不成功
NOTIFICATION_TITLE和NOTIFICATION_CONTENT不配置，流程中不配置，发送通知成功（只是一个本地的域名）
流程中配置，NOTIFICATION_TITLE和NOTIFICATION_CONTENT不配置，发送通知
流程中配置，NOTIFICATION_TITLE和NOTIFICATION_CONTENT配置，发送成功
结论：只要通知的标题和内容全部填写无论是单独还是通知配置引擎后台还是流程编辑器的通知都会发送引擎版本v2.0.20170711-230858

请问一下，在平台更新的时候是否是对通知的逻辑进行了更改，这三个版本的引擎我导入的同一个流程。但是得到的结果是不同的。阿里云版本的引擎测试5次，都是同样的结果，

**Comment by marstone** [comment]
逻辑上没有调整过。
造成差别的原因是：阿里云配置过Channel
NOTIFICATION_TITLE/CONTENT的配置是遗留配置，将来会完全取消掉。
目前的兼容逻辑是：
配置过Channel的，上述配置完全失效；没配过Channel的，作为默认Channel使用。

**Comment by liangyu1937** [comment]
杜老师，按照您的方法，我在阿里云的后台中，配置了channel中的TITLE/CONTENT，而NOTIFICATION_TITLE/CONTENT没有配置，
![default](https://user-images.githubusercontent.com/29417531/29511865-0bd3d7be-8693-11e7-8e6b-e0ce1aabd8f3.png)

在流程编辑器中，渠道选择了channel中的邮件，通知内容和标题没有填写，依然是没有收到通知。

**Comment by marstone** [comment]
抓图不全，Default是TRUE吗？

**Comment by liangyu1937** [comment]
Default更改为TRUE，使用通道，正常发送邮件通知
